[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = ""

[env]
PORT = "8000"
DATABASE_URL = "${{DATABASE_URL}}"
SUPABASE_URL = "${{SUPABASE_URL}}"
SUPABASE_ANON_KEY = "${{SUPABASE_ANON_KEY}}"
MODULE_NAME = "main"
VARIABLE_NAME = "app" 